name: CI/CD Flask

on:

  push:

    branches:

      - master

jobs:
  test:
    name: Exécuter les tests
    runs-on: ubuntu-latest

    steps:
      - name: Récuperer le code
        users: actions/checkout@v3

      - name: Installer python
        users: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run:  |
          python -m venv venv
          source  venv/bin/activate
          pip install flask

      - name: vérifier que Flask foncionne
        run: python app.py  &
