name: CI Flask App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m venv venv
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || python -m pip install flask

      - name: Lancer les tests
        run: python -m unittest discover tests

